name: Cleanup runs

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest

    permissions:
      actions: write   # ✅ GANZ WICHTIG

    steps:
      - name: Delete old runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run list --limit 1000 --json databaseId -q '.[].databaseId' | tail -n +6 | while read id; do
            gh run delete $id
          done
